carpentries-incubator/lesson-gpu-programming

README.md

First readme change.

---

_config.yml

Changed config file. Added title and email.

---

.gitignore
_config.yml
_episodes/01-introduction.md
_episodes/02-first_program.md
bin/lesson_initialize.py

Worked on the structure of Episodes 1 and 2.

Episode 1 and 2.

---

_episodes/02-cupy.md

Originally, this branch was created to add some examples to chapter 02, as an assignment from the Carpentries Lesson Study Group.
It evolved into an introduction to CuPy. So it should have all the contents for chapter 02.
So what I have added is simple code to convolve a regular grid of "delta functions" with a 2D symentrical Gaussian.
First, on the CPU, using Numpy and Scipy.
Next, on the GPU, using CuPy and cupyx.
Compare the runtimes and results.

A simple convolution example to provide a proper introduction to CuPy

---

_episodes/02-cupy.md

This should fix all the issues with episode 2 that we got from the review and the trial run.
So this fixes #9 and #10  
---

Update 02 based on review and trial run comments

---

_episodes/02-cupy.md

Episode 2 should now be complete with the addition of Numpy routines that operate on CuPy arrays.
Without any extra effort, they are executed on the GPU.
The idea is that one can speed up calculations with very little hassle.

Extend episode 2 with cpu/gpu agnostic code

---

_episodes/05-constant_memory.md

Merging because we are going to have a first pilot workshop next week, and we want to have the material available.

Constant memory

---

_episodes/02-cupy.md

The exercise is to compute all prime numbers between 1 and 10000 on the CPU and GPU using Python code. Numba will compile it for the GPU.
Start off with Python code for finding all primes in a certain interval. You can find this code all over the web.
Time it. Add a jit(nopython=True) decorator and time again.
Use Numba's vectorize decorator for the GPU.

Compute prime numbers between 1 and 10000 using Python code. 

---

_episodes/02-cupy.md

This is a response to the comments to  #19 but that branch has been deleted.
---

Add numba to episode 2

---

_episodes/03-numba.md

`Programming your GPU using Numba` seems an appropriate title to me.
---

Attempt to fix #28

---

_episodes/02-cupy.md

`Programming your GPU using CuPy` seems an appropriate title to me.
Fixes #27 
---

Attempt to fix #27

---

_episodes/03-numba.md

Remove decorator in challenge.

Remove decorator.

---

_episodes/02-cupy.md
_episodes/03-numba.md
_episodes/04-first_program.md

Fixes after 2021-11-02-ds-gpu

---

_episodes/07-shared_memory_and_synchronization.md

This pull requests aims at addressing issue #62 making the shared histogram exercise easier to understand.

Improve shared histogram exercise

---

_episodes/01-introduction.md
_episodes/02-cupy.md
fig/mapping.svg
fig/stencil.svg

This addition explains a few concepts that we're dealing with in the first two episodes. The figures used here are generated using my custom SVG generator [here](https://github.com/jhidding/svg-gen). Still work in progress.

Some improvements to the first two episodes

---

_episodes/05-first_program.md

The exercise has been modified to provide working, but highly inefficient, CUDA code, instead of no code at all. This should help students without experience in C with the syntax.
This pull requests closes issue #77 .

Prime number exercise

---

_episodes/07-shared_memory_and_synchronization.md

Improved the code in the shared memory episode.
Fix issue #63

Better performance measurements

---

_episodes/01-introduction.md
_episodes/02-cupy.md
_episodes/03-numba.md
_episodes/05-first_program.md

The measurements are now done appropriately also for CuPy and Numba, measurement technique is introduced at the right point, and the prime numbers code has been simplified.

Measurements and code improvements

---

_episodes/04-gpu-introduction.md
_episodes/05-first_program.md
_episodes/07-shared_memory_and_synchronization.md

Improve consistency in the coding style.

General code improvements

---

_episodes/04-gpu-introduction.md
_episodes/05-first_program.md
_episodes/07-shared_memory_and_synchronization.md

A small series of code improvements.

Small code improvements

---

index.md

Added the prerequisites we often use when teaching the course to the lesson.

Prerequisites

---

setup.md

Adds scipy and astropy as additional dependencies required for non-colab workshops

resolves #94: adds dependencies for non-colab

---

_episodes/05-first_program.md

This PR addresses task 2 in #97 of adding a more complete snippet for the final section comparing cpu and gpu arrays for vectors of arbitrary size

adding complete snippet for large arrays section

---

index.md

Fixes #107 
I didn't test if this renders correctly

Add callout to attract users

---

renv/activate.R
renv/profiles/lesson-requirements/renv.lock

Fixes `compilation failed for package 'yaml'` https://github.com/carpentries-incubator/lesson-gpu-programming/actions/runs/10556466260/job/29242081106

Sync renv with template to fix 'compilation failed for package 'yaml'' in workbench build

---

README.md
workshops.md

@isazi do you know of any external editions? Please fill in missing info in the workshops.md table.

Add overview of workshops using the lesson material
